// Mock data for when there are no real posts available
export const mockUsers = [
  {
    id: 'mock-1',
    name: 'Sarah Green',
    username: '@sarahgreen',
    avatar: 'https://images.unsplash.com/photo-1494790108755-2616b612b786?w=150&h=150&fit=crop&crop=face',
    followers: 1250,
    following: 340,
    specialty: 'Organic Farming',
  },
  {
    id: 'mock-2',
    name: 'Mike Harvest',
    username: '@mikeharvest',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&h=150&fit=crop&crop=face',
    followers: 890,
    following: 210,
    specialty: 'Permaculture',
  },
  {
    id: 'mock-3',
    name: 'Emma Fields',
    username: '@emmafields',
    avatar: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=150&h=150&fit=crop&crop=face',
    followers: 2100,
    following: 450,
    specialty: 'Urban Gardening',
  },
  {
    id: 'mock-4',
    name: 'David Soil',
    username: '@davidsoil',
    avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&h=150&fit=crop&crop=face',
    followers: 750,
    following: 180,
    specialty: 'Climate Science',
  },
  {
    id: 'mock-5',
    name: 'Lisa Bloom',
    username: '@lisabloom',
    avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&h=150&fit=crop&crop=face',
    followers: 1680,
    following: 320,
    specialty: 'Sustainable Tech',
  },
];

export const mockTrendingTopics = [
  { id: 1, tag: '#SustainableFarming', icon: '🌱', posts: '127' },
  { id: 2, tag: '#OrganicGardening', icon: '🌿', posts: '89' },
  { id: 3, tag: '#ClimateChange', icon: '🌍', posts: '156' },
  { id: 4, tag: '#GreenTech', icon: '♻️', posts: '73' },
  { id: 5, tag: '#PermaCulture', icon: '🌳', posts: '94' },
];

export const mockDiscoverPosts = [
  {
    id: 'discover-1',
    image: 'https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=400&h=400&fit=crop',
    likes: '45',
    title: 'Beautiful tomato harvest...',
  },
  {
    id: 'discover-2',
    image: 'https://images.unsplash.com/photo-1464226184884-fa280b87c399?w=400&h=400&fit=crop',
    likes: '78',
    title: 'Sustainable farming methods...',
  },
  {
    id: 'discover-3',
    image: 'https://images.unsplash.com/photo-1500937386664-56d1dfef3854?w=400&h=400&fit=crop',
    likes: '92',
    title: 'Urban garden setup...',
  },
  {
    id: 'discover-4',
    image: 'https://images.unsplash.com/photo-1574323347407-f5e1ad6d020b?w=400&h=400&fit=crop',
    likes: '34',
    title: 'Organic vegetables growing...',
  },
  {
    id: 'discover-5',
    image: 'https://images.unsplash.com/photo-1592419044706-39796d40f98c?w=400&h=400&fit=crop',
    likes: '67',
    title: 'Greenhouse innovations...',
  },
  {
    id: 'discover-6',
    image: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400&h=400&fit=crop',
    likes: '123',
    title: 'Permaculture design...',
  },
];

export const mockPosts = [
  {
    id: 'mock-post-1',
    user: mockUsers[0],
    content: 'Just harvested the most amazing organic tomatoes from my greenhouse! The taste difference is incredible when you grow them with love and sustainable practices. 🍅✨',
    image: 'https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=600&h=400&fit=crop',
    timestamp: '2h ago',
    likes: 45,
    comments: 12,
    shares: 3,
    isLiked: false,
    isShared: false,
    moderationStatus: 'approved' as const,
    isAgricultureRelated: true,
    aiScore: 0.95,
    aiTags: ['organic', 'tomatoes', 'greenhouse', 'sustainable'],
    recommendationScore: 0.9,
  },
  {
    id: 'mock-post-2',
    user: mockUsers[1],
    content: 'Implementing permaculture principles in my backyard has transformed not just my garden, but my entire relationship with nature. Here\'s what I\'ve learned after 2 years...',
    image: 'https://images.unsplash.com/photo-1464226184884-fa280b87c399?w=600&h=400&fit=crop',
    timestamp: '5h ago',
    likes: 78,
    comments: 23,
    shares: 8,
    isLiked: false,
    isShared: false,
    moderationStatus: 'approved' as const,
    isAgricultureRelated: true,
    aiScore: 0.92,
    aiTags: ['permaculture', 'sustainable', 'gardening'],
    recommendationScore: 0.88,
  },
  {
    id: 'mock-post-3',
    user: mockUsers[2],
    content: 'Urban farming doesn\'t have to be complicated! Started this vertical garden on my apartment balcony with just $50 and some creativity. Growing my own herbs and leafy greens! 🌿',
    image: 'https://images.unsplash.com/photo-1500937386664-56d1dfef3854?w=600&h=400&fit=crop',
    timestamp: '1d ago',
    likes: 92,
    comments: 18,
    shares: 15,
    isLiked: true,
    isShared: false,
    moderationStatus: 'approved' as const,
    isAgricultureRelated: true,
    aiScore: 0.89,
    aiTags: ['urban farming', 'vertical garden', 'herbs'],
    recommendationScore: 0.85,
  },
  {
    id: 'mock-post-4',
    user: mockUsers[3],
    content: 'Climate change is real, but so is our power to make a difference. Every small action in sustainable agriculture counts. Here\'s how we can adapt our farming practices...',
    timestamp: '2d ago',
    likes: 156,
    comments: 45,
    shares: 32,
    isLiked: false,
    isShared: true,
    moderationStatus: 'approved' as const,
    isAgricultureRelated: true,
    aiScore: 0.94,
    aiTags: ['climate change', 'sustainable agriculture', 'adaptation'],
    recommendationScore: 0.91,
  },
  {
    id: 'mock-post-5',
    user: mockUsers[4],
    content: 'Excited to share our new IoT sensors for monitoring soil moisture and pH levels! Technology and agriculture working together for better yields and resource efficiency. 📊🌱',
    image: 'https://images.unsplash.com/photo-1574323347407-f5e1ad6d020b?w=600&h=400&fit=crop',
    timestamp: '3d ago',
    likes: 67,
    comments: 14,
    shares: 6,
    isLiked: false,
    isShared: false,
    moderationStatus: 'approved' as const,
    isAgricultureRelated: true,
    aiScore: 0.87,
    aiTags: ['IoT', 'soil monitoring', 'technology', 'efficiency'],
    recommendationScore: 0.83,
  },
];